name: build and publish main

on:
  # push: 
  #   branches:
  #     - code
  workflow_dispatch: 

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: pull codde
        uses: actions/checkout@v3
      
      - name: set node env
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: install dep
        run: npm ci
      
      - name: build 
        run: npm run build
    
